package vista;

import bbdd.Seleccionar;
import static bbdd.Seleccionar.alumnos;
import static bbdd.Seleccionar.volumenes;
import controlador.ControladorListaVolumenes;
import java.awt.Image;
import java.util.*;
import javax.swing.*;
import modeloAlumno.*;
import java.lang.*;
import javax.swing.table.DefaultTableModel;
import modeloVolumen.Volumen;

public class CrearLote extends javax.swing.JFrame {

    /**
     * Creates new form CrearLote
     */
    public CrearLote() {
        initComponents();
        setTitle("Crear Lote");
        setLocationRelativeTo(null);
        ImageIcon imageIcon = new ImageIcon("imagenes\\icono_alumno.jpg");
        Image image = imageIcon.getImage(); // transform it 
        Image newimg = image.getScaledInstance(20, 20,  java.awt.Image.SCALE_SMOOTH); // scale it the smooth way  
        imageIcon = new ImageIcon(newimg);
        jButtonBuscarAlumno.setIcon(imageIcon);
        
        model.addColumn("Volumen");
        model.addColumn("ISBN");
        model.addColumn("Editorial");
        model.addColumn("Número de Volumen");
        model.addColumn("Cantidad de Volumenes");
        jTable1.setModel(model);
        
        Seleccionar.buscarTodosVolumenes();
        for(int i = 0; i < volumenes.longitud(); i++){
            v = c.getVolumenP(i);
            añadirFila();
        }
    }
    
    static DefaultTableModel model = new DefaultTableModel();
    static Object[] o = new Object[5];
    static Volumen v = new Volumen();
    ControladorListaVolumenes c = new ControladorListaVolumenes();
    
    public static void añadirFila(){
        o[0] = v.getTitulo();
        o[1] = v.getIsbn();
        o[2] = v.getEditorial();
        o[3] = v.getNumVolumen();
        o[4] = v.getCantVolumenes();
        model.addRow(o);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButtonBuscarAlumno = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabelNombre = new javax.swing.JLabel();
        jLabelApellido1 = new javax.swing.JLabel();
        jLabelApellido2 = new javax.swing.JLabel();
        jLabelNIA = new javax.swing.JLabel();
        jLabelEnsenyanza = new javax.swing.JLabel();
        jLabelNumCurso = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Crear un Lote");

        jButtonBuscarAlumno.setText("Buscar Alumno");
        jButtonBuscarAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarAlumnoActionPerformed(evt);
            }
        });

        jLabel2.setText("Nombre:");

        jLabel3.setText("Primer Apellido:");

        jLabel4.setText("Segundo Apellido:");

        jLabel5.setText("NIA:");

        jLabel6.setText("Enseñanza:");

        jLabel7.setText("Curso:");

        jButton1.setText("Volver");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                    .addComponent(jLabelNIA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelApellido1, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE)
                    .addComponent(jLabelEnsenyanza, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel4))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelApellido2, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                    .addComponent(jLabelNumCurso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(41, 41, 41))
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator1)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1002, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(465, 465, 465)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonBuscarAlumno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jButtonBuscarAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabelNombre)
                    .addComponent(jLabelApellido1)
                    .addComponent(jLabelApellido2))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabelNIA)
                    .addComponent(jLabelEnsenyanza)
                    .addComponent(jLabelNumCurso))
                .addGap(54, 54, 54)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 138, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBuscarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarAlumnoActionPerformed
        ActualizarAlumno a = new ActualizarAlumno();
        a.setVisible(true);
        ActualizarAlumno.jButtonActualizar.setEnabled(false);

//        String alumno = jTextFieldAlumno.getText();
//        
//        //Vaciar lista de alumnos
//        alumnos.borrar();
//        
//        BuscarAlumno b = new BuscarAlumno();
//        try {
//            if(jComboBox1.getSelectedItem().toString().equals("Por NIA")){  
//                Seleccionar.buscarAlumnoNIA(Integer.parseInt(alumno));
//
//                //BuscarAlumno b = new BuscarAlumno();
//                b.setVisible(true);
//
//                DefaultListModel listModel = new DefaultListModel();
//
//                for(int i = 0; i < alumnos.longitud(); i++){
//                    a = alumnos.getAlumno(i);
//                    String sApellido = a.getApellido2();
//                    if (sApellido.equals("null")){
//                        sApellido = "";
//                    }
//                    listModel.addElement(a.getNombre() + " " + a.getApellido1() + " " + sApellido);
//
//                    BuscarAlumno.jListAlumnos.setModel(listModel);
//                }
//            } else if(jComboBox1.getSelectedItem().toString().equals("Por Nombre")){
//                Seleccionar.buscarAlumnoNombre(alumno);
//
//                //BuscarAlumno b = new BuscarAlumno();
//                b.setVisible(true);
//
//                DefaultListModel listModel = new DefaultListModel();
//
//                for(int i = 0; i < alumnos.longitud(); i++){
//                    a = alumnos.getAlumno(i);
//                    String sApellido = a.getApellido2();
//                    if (sApellido.equals("null")){
//                        sApellido = "";
//                    }
//                    listModel.addElement(a.getNombre() + " " + a.getApellido1() + " " + sApellido);
//
//                    BuscarAlumno.jListAlumnos.setModel(listModel);
//                }
//            } else if(jComboBox1.getSelectedItem().toString().equals("Por Primer Apellido")){
//                Seleccionar.buscarAlumnoPrimerApellido(alumno);
//
//                //BuscarAlumno b = new BuscarAlumno();
//                b.setVisible(true);
//
//                DefaultListModel listModel = new DefaultListModel();
//
//                for(int i = 0; i < alumnos.longitud(); i++){
//                    a = alumnos.getAlumno(i);
//                    String sApellido = a.getApellido2();
//                    if (sApellido.equals("null")){
//                        sApellido = "";
//                    }
//                    listModel.addElement(a.getNombre() + " " + a.getApellido1() + " " + sApellido);
//
//                    BuscarAlumno.jListAlumnos.setModel(listModel);
//                }
//            }
//        } catch (NullPointerException | NumberFormatException e){
//            JOptionPane.showMessageDialog(null, "Introduce algún parametro para búsqueda");
//            b.setVisible(false);
//        }
//        String nombre = "";
//        String apellido = "";
//        StringTokenizer n = new StringTokenizer(alumno);
//        try {
//            if (n.countTokens()>1){
//                while(n.hasMoreTokens()){
//                    nombre = n.nextToken();
//                    apellido = n.nextToken();
//                }
//                Seleccionar.buscarAlumnoNombreApellido(nombre, apellido);
//
//                BuscarAlumno b = new BuscarAlumno();
//                b.setVisible(true);
//
//                DefaultListModel listModel = new DefaultListModel();
//                Alumno a;
//                for (int i = 0; i < alumnos.longitud(); i++){
//                    a = alumnos.getAlumno(i);
//
//                    listModel.addElement(a.getNombre()+" "+a.getApellido1()+" "+a.getApellido2());
//                    BuscarAlumno.jListAlumnos.setModel(listModel);
//                }
//            } else if (n.countTokens() == 1) {
//                Seleccionar.buscarAlumnoNombre(alumno);
//                
//                BuscarAlumno b = new BuscarAlumno();
//                b.setVisible(true);
//
//                DefaultListModel listModel = new DefaultListModel();
//                Alumno a;
//                for (int i = 0; i < alumnos.longitud(); i++){
//                    a = alumnos.getAlumno(i);
//
//                    listModel.addElement(a.getNombre()+" "+a.getApellido1()+" "+a.getApellido2());
//                    BuscarAlumno.jListAlumnos.setModel(listModel);
//                }
//            } else {
//                while(n.hasMoreTokens()){
//                    nombre = n.nextToken();
//                    apellido = n.nextToken();
//                }
//                Seleccionar.buscarAlumnoNombreApellido(nombre, apellido);
//
//                BuscarAlumno b = new BuscarAlumno();
//                b.setVisible(true);
//
//                DefaultListModel listModel = new DefaultListModel();
//                Alumno a;
//                for (int i = 0; i < alumnos.longitud(); i++){
//                    a = alumnos.getAlumno(i);
//
//                    listModel.addElement(a.getNombre()+" "+a.getApellido1()+" "+a.getApellido2());
//                    BuscarAlumno.jListAlumnos.setModel(listModel);
//                }
//            }
//        } catch(Exception e){
//            JOptionPane.showMessageDialog(null, "Introduce nombre y primer apellido");
//            jTextFieldAlumno.setText("");
//        }

    }//GEN-LAST:event_jButtonBuscarAlumnoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearLote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearLote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearLote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearLote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrearLote().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonBuscarAlumno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    public static javax.swing.JLabel jLabelApellido1;
    public static javax.swing.JLabel jLabelApellido2;
    public static javax.swing.JLabel jLabelEnsenyanza;
    public static javax.swing.JLabel jLabelNIA;
    public static javax.swing.JLabel jLabelNombre;
    public static javax.swing.JLabel jLabelNumCurso;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
