package vista;

import bbdd.Ficheros;
import static bbdd.Ficheros.*;
import bbdd.Conexion;
import java.awt.*;
import java.io.*;
import java.net.URL;
import javax.help.*;
import javax.swing.*;
import static vista.ActualizarAlumno.jButtonAceptar;

public class Principal extends javax.swing.JFrame {
    private static String OS = System.getProperty("os.name").toLowerCase();
    private static String dir = System.getProperty("user.dir");
    
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Banco de Libros");
        //la imagen de libros
        ImageIcon imageIcon = new ImageIcon("src\\imagenes\\libros.png");
        Image image = imageIcon.getImage(); // transform it 
        Image newimg = image.getScaledInstance(120, 120,  java.awt.Image.SCALE_SMOOTH); // scale it the smooth way  
        imageIcon = new ImageIcon(newimg);  // transform it back
        jLabelImagen.setIcon(imageIcon);
        //icono en la barra
        setIconImage(newimg);
        verAyuda();
        jButtonRecogerLibros.setEnabled(false);
    }
    
    public static boolean isWindows() {
        return (OS.indexOf("win") >= 0);
    }
    
    private void verAyuda() {
	try {
            // Carga el fichero de ayuda
            if(isWindows()){
                File fichero = new File(dir + "\\help\\help_set.hs");
                URL hsURL = fichero.toURI().toURL();
                
                // Crea el HelpSet y el HelpBroker
                HelpSet helpset = new HelpSet(getClass().getClassLoader(), hsURL);
                HelpBroker hb = helpset.createHelpBroker();

                // Pone ayuda a item de menu al pulsarlo y a F1 en ventana
                // principal y secundaria.
                hb.enableHelpOnButton(jButtonAlta, "aplicacion", helpset);
                hb.enableHelpKey(getRootPane(), "ventana_principal", helpset);
                hb.enableHelpKey(Ayuda, "ventana_principal", helpset);
            } else {
                File fichero = new File(dir + "/help/help_set.hs");
                URL hsURL = fichero.toURI().toURL();
                
                // Crea el HelpSet y el HelpBroker
                HelpSet helpset = new HelpSet(getClass().getClassLoader(), hsURL);
                HelpBroker hb = helpset.createHelpBroker();

                // Pone ayuda a item de menu al pulsarlo y a F1 en ventana
                // principal y secundaria.
                hb.enableHelpOnButton(jButtonAlta, "aplicacion", helpset);
                hb.enableHelpKey(getRootPane(), "ventana_principal", helpset);
                hb.enableHelpKey(Ayuda, "ventana_principal", helpset);
            }
	} catch (Exception e) {
            e.printStackTrace();
	}
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        jButtonRepartirLibros = new javax.swing.JButton();
        jButtonRecogerLibros = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();
        jLabelImagen = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuImportar = new javax.swing.JMenu();
        jMenuItemAlumnos = new javax.swing.JMenuItem();
        jMenuItemVolumenes = new javax.swing.JMenuItem();
        jMenuItemAsignaturas = new javax.swing.JMenuItem();
        jMenuGestion = new javax.swing.JMenu();
        jMenuItemAnyadir = new javax.swing.JMenuItem();
        jMenuItemActualizar = new javax.swing.JMenuItem();
        Ayuda = new javax.swing.JMenu();
        jButtonAlta = new javax.swing.JMenuItem();

        jMenu2.setText("File");
        jMenuBar2.add(jMenu2);

        jMenu3.setText("Edit");
        jMenuBar2.add(jMenu3);

        jMenu5.setText("jMenu5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Banco de Libros");

        jButtonRepartirLibros.setText("Repartir Libros");
        jButtonRepartirLibros.setPreferredSize(new java.awt.Dimension(120, 25));
        jButtonRepartirLibros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRepartirLibrosActionPerformed(evt);
            }
        });

        jButtonRecogerLibros.setText("Recoger Libros");
        jButtonRecogerLibros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRecogerLibrosActionPerformed(evt);
            }
        });

        jButtonSalir.setText("Salir");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });

        jMenuImportar.setText("Importar");
        jMenuImportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuImportarActionPerformed(evt);
            }
        });

        jMenuItemAlumnos.setText("Importar Alumnos");
        jMenuItemAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAlumnosActionPerformed(evt);
            }
        });
        jMenuImportar.add(jMenuItemAlumnos);

        jMenuItemVolumenes.setText("Importar Volumenes");
        jMenuItemVolumenes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemVolumenesActionPerformed(evt);
            }
        });
        jMenuImportar.add(jMenuItemVolumenes);

        jMenuItemAsignaturas.setText("Importar Asignaturas");
        jMenuItemAsignaturas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAsignaturasActionPerformed(evt);
            }
        });
        jMenuImportar.add(jMenuItemAsignaturas);

        jMenuBar1.add(jMenuImportar);

        jMenuGestion.setText("Gestión de Alumnos");
        jMenuGestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuGestionActionPerformed(evt);
            }
        });

        jMenuItemAnyadir.setText("Añadir Nuevo Alumno");
        jMenuItemAnyadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAnyadirActionPerformed(evt);
            }
        });
        jMenuGestion.add(jMenuItemAnyadir);

        jMenuItemActualizar.setText("Actualizar Datos de Alumno");
        jMenuItemActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemActualizarActionPerformed(evt);
            }
        });
        jMenuGestion.add(jMenuItemActualizar);

        jMenuBar1.add(jMenuGestion);

        Ayuda.setText("Ayuda");

        jButtonAlta.setText("Mostrar Ayuda");
        Ayuda.add(jButtonAlta);

        jMenuBar1.add(Ayuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jButtonRepartirLibros, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(jButtonRecogerLibros, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jButtonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabelImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addComponent(jButtonRepartirLibros, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(jButtonRecogerLibros, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(38, 38, 38)
                .addComponent(jButtonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRepartirLibrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRepartirLibrosActionPerformed
        RepartirLibros r = new RepartirLibros();
        r.setVisible(true);
    }//GEN-LAST:event_jButtonRepartirLibrosActionPerformed

    private void jButtonRecogerLibrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRecogerLibrosActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButtonRecogerLibrosActionPerformed

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jMenuImportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuImportarActionPerformed
        
    }//GEN-LAST:event_jMenuImportarActionPerformed

    private void jMenuItemAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAlumnosActionPerformed
        JFileChooser frame = new JFileChooser();
        frame.setVisible(true);
        frame.showOpenDialog(frame);
        try {
            if (frame.isFileSelectionEnabled()) {
                Conexion.Conectar();
                File fichero = frame.getSelectedFile();
                String f = fichero.getAbsolutePath();
                borrarTablaAlumno();
                importarFicheroAlumnos(f);
                System.out.println(f);
                JOptionPane.showMessageDialog(null, "El fichero se ha importado con éxito");
            }
        } catch (Exception n) {
            JOptionPane.showMessageDialog(null, "No ha eligido ningún fichero");
        }
    }//GEN-LAST:event_jMenuItemAlumnosActionPerformed

    private void jMenuItemVolumenesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemVolumenesActionPerformed
        JFileChooser frame = new JFileChooser();
        frame.setVisible(true);
        frame.showOpenDialog(frame);
        try {
            if (frame.isFileSelectionEnabled()) {
                Conexion.Conectar();
                File fichero = frame.getSelectedFile();
                String f = fichero.getAbsolutePath();
                borrarTablaVolumen();
                importarFicheroVolumenes(f);
                System.out.println(f);
                JOptionPane.showMessageDialog(null, "El fichero se ha importado con éxito");
            }
        } catch (Exception n) {
            JOptionPane.showMessageDialog(null, "No ha eligido ningún fichero");
        }
    }//GEN-LAST:event_jMenuItemVolumenesActionPerformed

    private void jMenuItemAsignaturasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAsignaturasActionPerformed
        JFileChooser frame = new JFileChooser();
        frame.setVisible(true);
        frame.showOpenDialog(frame);
        try {
            if (frame.isFileSelectionEnabled()) {
                Conexion.Conectar();
                File fichero = frame.getSelectedFile();
                String f = fichero.getAbsolutePath();
                borrarTablaAsignatura();
                importarFicheroAsignaturas(f);
                System.out.println(f);
                JOptionPane.showMessageDialog(null, "El fichero se ha importado con éxito");
            }
        } catch (Exception n) {
            JOptionPane.showMessageDialog(null, "No ha eligido ningún fichero");
        }
    }//GEN-LAST:event_jMenuItemAsignaturasActionPerformed

    private void jMenuGestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuGestionActionPerformed
        
    }//GEN-LAST:event_jMenuGestionActionPerformed

    private void jMenuItemAnyadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAnyadirActionPerformed
        AnyadirAlumno a = new AnyadirAlumno();
        a.setVisible(true);
    }//GEN-LAST:event_jMenuItemAnyadirActionPerformed

    private void jMenuItemActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemActualizarActionPerformed
        ActualizarAlumno a = new ActualizarAlumno();
        a.setVisible(true);
        jButtonAceptar.setEnabled(false);
    }//GEN-LAST:event_jMenuItemActualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Ayuda;
    private javax.swing.JMenuItem jButtonAlta;
    private javax.swing.JButton jButtonRecogerLibros;
    private javax.swing.JButton jButtonRepartirLibros;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelImagen;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenu jMenuGestion;
    private javax.swing.JMenu jMenuImportar;
    private javax.swing.JMenuItem jMenuItemActualizar;
    private javax.swing.JMenuItem jMenuItemAlumnos;
    private javax.swing.JMenuItem jMenuItemAnyadir;
    private javax.swing.JMenuItem jMenuItemAsignaturas;
    private javax.swing.JMenuItem jMenuItemVolumenes;
    // End of variables declaration//GEN-END:variables
}
